### ISSUE TITLE
AddHook on compose

### ISSUE THREAD

**Issue by lsfera** [mariotoffia/FluentDocker#104]
AddHook with compose file is not triggered when container name is
- specified 
- different by its service name.

```
version: '3.4'
services:
  mssql: 
    container_name: mssql1
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1434:1433"
    environment:
      MSSQL_DB: Chromosome
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
```
code for test
```
private static Int32 counter = 0;
using (var svc = new Builder()
	.UseContainer()
	.UseCompose()
	.FromFile(file)
	.RemoveOrphans()
	.Wait("mssql", (service, i) => CheckConnection(service, i))
	.Build().Start())
	{
            Assert.That(counter, Is.GreaterThan(0));
	}

private static int CheckConnection(IContainerService service, int i)
{
	try
	{
		return counter++;
	}
	catch
	{
		return 500 /*ms*/;
	}
}
```
