### ISSUE TITLE
Adding labels to images build via fluent api or from dockerfile

### ISSUE THREAD

**Issue by aslezak** [mariotoffia/FluentDocker#147]
Hi,
this might be a bit of specific case, but I would like to ask if there is support for adding labels to images that were built and are then used to stand up containers via the fluent API?

```csharp
_builder = builder.UseContainer()
                              .WithEnvironment()
                              .UseCompose()
                              .FromFile(ComposeFilePaths)
                              .ServiceName(ComposeProjectName)
                              .RemoveOrphans()
                              .WaitForPort(ComposeProjectName, $"{PrivateServicePort.Port}/tcp", ServiceWaitTime);

_builder.Build(); // --> as a parameter here would be nice to be able to add a label or labels in string[] to resulting images to be able to later clean them up on CI agents and such.
```
Alternatively also defining multiple tags would also be an option.

Thank you

**Comment by mariotoffia** [comment]
Hi @aslezak - is it this that you're looking for (compose 3.3+)?
```yaml
build:
  context: .
  labels:
    com.example.description: "Accounting webapp"
    com.example.department: "Finance"
    com.example.label-with-empty-value: ""
```
[Compose: labels](https://docs.docker.com/compose/compose-file/#labels)

Or do you need to specify those in the code (_FluentAPI_) itself?

Cheers, 
 Mario :)

**Comment by aslezak** [comment]
Exactly that, but adding that ability in _FluentApi_ itself would allow for dynamic tags based on build parameters like build number, commit hash etc.

**Comment by mariotoffia** [comment]
I see, since I'm still a bit reluctant to introduce additional dependencies (such as a yaml parser) - that will have to wait until 3.0.0 or 4.0.0. I'm thinking of adding the possibility to pass envirinment variable through the _FluentAPI_ and thus it is possible to use those in the compose file like this.

Given:
```yaml
build:
  context: .
  labels:
    - "com.example.description=${DESCRIPTION}"
    - "${CUSTOM_NAME}=${CUSTOM_VALUE}"
```
Set environment for the Compose in the _FluentAPI_:
```cs
Fd.UseContainer()
	.WithEnvironment()	
	.UseCompose()
	.FromFile(ComposeFilePaths)
	.ServiceName(ComposeProjectName)
	.WithEnvironment(
		$"DESCRIPTION={description}",
		$"CUSTOM_NAME={buildname}",
		$"CUSTOM_VALUE={buildtag}")	
	.RemoveOrphans()	
	.WaitForPort(ComposeProjectName, $"{PrivateServicePort.Port}/tcp", ServiceWaitTime)
	.Build();
```

Would that be fine for now? (around the lines)?

Cheers,
 Mario :)

**Comment by aslezak** [comment]
Yes, should be enough for now, I didn't realize that environment variables can be used that way.

Also for the actual solution, I don't think yaml parsing would be necessary as it is just adding of a parameter to docker build command, at least when building an image from builder and not via compose. Unless under the hood the builder uses the Dockerfile to build the image? I didn't dig into it quite yet.

Thanks for the quick solve idea!

**Comment by mariotoffia** [comment]
@aslezak I've done a pre-release for this feature, please test it and let me know if it works ok for you?

**Comment by aslezak** [comment]
Great thank you, I will test it today

**Comment by mariotoffia** [comment]
@aslezak How did it go?

**Comment by aslezak** [comment]
Hi, sorry, a bit overloaded with other projects, I will try to get to it with some free time over the weekend! sorry for the delay.

**Comment by mariotoffia** [comment]
@aslezak I'm closing this issue now. If you get in to some sort of a problem with this fix - please re-open this issue.

Cheers,
 Mario

**Comment by gitfool** [comment]
@mariotoffia I just tried the beta because I need to pass dynamically calculated environment variables to docker compose.

`docker-compose.yml`:
```yml
version: "3.0"

services:
  test-service:
    build:
      context: ../Service
      dockerfile: Dockerfile
    ports:
      - 8080
    image: pharos/testing:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      OtherService__BaseUrl: ${MOCK_SERVICE_URL}/OtherService


  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000
```
Source:
```c#
var builder = CreateBuilder()
    .UseContainer()
    .UseCompose()
    .FromFile(Configuration.ComposeFiles)
    .ServiceName(Configuration.ProjectName)
    .WithEnvironment(environment)
    .RemoveOrphans()
    .ForceRecreate()
    .WaitForPort(Configuration.ProjectName, Configuration.Service.PortAndProtocol, (int)Configuration.ServiceWaitTime.TotalMilliseconds);
```

`environment` strings:
```
MOCK_SERVICE_URL=http://host.docker.internal:35079
Serilog__WriteTo__0__Name=Seq
Serilog__WriteTo__0__Args__serverUrl=http://host.docker.internal:5341
Serilog__MinimumLevel__Default=Information
Serilog__MinimumLevel__Override__Microsoft.Hosting.Lifetime=Information
Serilog__MinimumLevel__Override__Microsoft.AspNetCore=Warning
Serilog__MinimumLevel__Override__Microsoft=Information
```
Unfortunately, I don't see the extra environment variables inside the container. I only see the ones specified in the `docker-compose.yml`. 😕
