### ISSUE TITLE
Unable to CopyOnStart for DockerCompose

### ISSUE THREAD

**Issue by DR9885** [mariotoffia/FluentDocker#175]
When I try to "CopyOnStart" for a docker-composed service it doesn't seem to copy. 

C# code
```
var composeService = new Builder()
                .UseContainer()
                .UseCompose()
                .FromFile(file)
                .RemoveOrphans()
                .CopyOnStart("mongodb-primary", $"Static{Path.DirectorySeparatorChar}dump", $"tmp{Path.DirectorySeparatorChar}dump")
```

Docker Compose
```
version: '2'

services:
  mongodb-primary:
    image: 'docker.io/bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password123
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - "27018:27017"

  mongodb-secondary:
    image: 'docker.io/bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local

```
