### ISSUE TITLE
RemoveNonTaggedImages is not working because image gets `latest` tag when not specified

### ISSUE THREAD

**Issue by szczepanbh** [mariotoffia/FluentDocker#190]
I'm not specifying a tag for my image in `docker-compose.yml `

```yml
version: "3.4"

services:
  my-api:
    image: my.api
    build:
      context: my.API
      dockerfile: Dockerfile
    ports:
      - "5005:80"
```
After running builder with `docker-compose.yml` file like this 
```
            _compositeService = new Builder()
                .UseContainer()
                .FromComposeFile(dockerComposePath)
                .RemoveOrphans()
                .RemoveNonTaggedImages()
                .ForceBuild()
                .WaitForHttp("my-api", $"{confirmUrl}/courses",
                    continuation: (response, _) => response.Code != HttpStatusCode.OK ? 5000 : 0)
                .Build()
                .Start();
```

my image `my-api`  has tag `latest` 

<a href="https://imgur.com/SoNctym"><img src="https://i.imgur.com/SoNctym.jpg" title="source: imgur.com" /></a>

so `RemoveNonTaggedImages()` which is adding `--rmi local` to `docker-compose down` is not removing this image.
