### ISSUE TITLE
Add support for --project-directory

### ISSUE THREAD

**Issue by R0Wi** [mariotoffia/FluentDocker#216]
First of all thanks for creating this awesome library!

I have a question which might result in a feature request. My current setup contains two different `docker-compose.yml` files in two different directories (let's call them `docker-compose.v1.yml` and `docker-compose.v2.yml`). I want to set `docker-compose.v1.yml` as my base file and then have some test specific overrides in `docker-compose.v2.yml`, which especially override some relative host mount points i need for my tests. 

`docker-compose.v1.yml`:
```yaml
version: '2.4'
services:
  s1:
    # ... 
    volumes:
        - ./myprodfiles:/etc/files
```

`docker-compose.v2.yml`:
```yaml
version: '2.4'
services:
  s1:
    # ... 
    volumes:
        - ./mytestfiles:/etc/files
```

So what i would do in my console is something like

```bash
docker-compose -f ../../../docker-compose.v1.yml -f ./docker-compose.v2.yml --project-directory . up
```

The important part is the `--project-directory` parameter (see https://docs.docker.com/compose/reference/). If i omit this parameter, docker-compose would try to resolve all relative host mount points to the first given `docker-compose.yml`-file (`docker-compose.v1.yml` in that case). But i would like to have my relative paths resolved relative to `docker-compose.v2.yml`, so relative to the current directory. According to the docs (see link above):

> When you use multiple Compose files, all paths in the files are relative to the first configuration file specified with -f. You can use the --project-directory option to override this base path.

**Question:** is it possible to achieve this with `FluentDocker` library? Unfortunately i did not find a possibility to add the `--project-directory`-parameter and i did not find any workaround neither.

Thanks so much!
