### ISSUE TITLE
Fluent API to Wait for Port or Process in Compose Based Services

### ISSUE THREAD

**Issue by mariotoffia** [mariotoffia/FluentDocker#62]
When e.g. firing up a wordpress using a docker-compose.yml file. There's no good way of expressing a wait condition in the fluent API. Instead it has to be done when the compose service is returned, select which service to wait for and wait manually.

This issue is about adding WaitForPort and WaitForProcess and specifying the service name (matching service in the docker-compose.yml).

Given the example of wordpress:
```cs
    using (var svc = new Builder()
                        .UseContainer()
                        .UseCompose()
                        .FromFile(file)
                        .RemoveOrphans()
                        .Build().Start())
      {
      }
```
and docker-compose file:
```yml
version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
```

Thus:
```cs
    builder.WaitForPort("5432/tcp", 30000 /*30s*/);
``` 
will become
```cs
    // service wordpress is the http server
    builder.WaitForPort("wordpress","5432/tcp", 30000 /*30s*/); 
``` 
and
```cs
    builder.WaitForProcess("postgres", 30000 /*30s*/);
``` 
will become
```cs
    // service db is the MySQL db
    builder.WaitForProcess("db", "mysql", 30000 /*30s*/);
```

It shall allow for multiple wait expressions and run them in order.
