### ISSUE TITLE
Dockerfile "arg" support and dockerfile "context"

### ISSUE THREAD

**Issue by Rhobil** [mariotoffia/FluentDocker#73]
Hi,

is it possible to pass build time variables (arg) to a dockerfile used with the "fromFile" extension?
And how can I set the context path for the dockerfile / whats the default context?
Example usage of args in a docker compose:

```
...
services:
  webapp:
    build:
      context: ./dir <--------------
      dockerfile: Dockerfile
      args: <----------------------
        myArgName: 123
...

```
thank you in advance

Edit:
I guess i found out how to set the context:  .WorkingFolder("<contextPath>")
