### ISSUE TITLE
DockerComposeCompositeService uses context of first compose file

### ISSUE THREAD

**Issue by Rhobil** [mariotoffia/FluentDocker#74]
Hi,

i tried to use DockerComposeCompositeService with 2 compose files. I defined a service with a dockerfile build definition in the second one. 

```
version: '3.7'

services:
  testservice:
    build:
      context: .
      dockerfile: Dockerfile
```

The problem is, that docker compose does not find the dockerfile. Its in the same folder as the second docker-compose file is located. If I put the dockerfile into the same folder as the first docker-compose is located, the file is found (but does not work anymore, files to copy into the docker container are at the seconds compose file position ;) ).

Can this be fixed? :)
(Version 2.6.4)
