### ISSUE TITLE
Compose Up for a specific machine

### ISSUE THREAD

**Issue by ivanrusso** [mariotoffia/FluentDocker#79]
How can composeUp be called with a compose file on a specific machine?

**Comment by mariotoffia** [comment]
You have to specify the host url to the machine - have a look at [connecting to remote daemon](https://github.com/mariotoffia/FluentDocker#connecting-to-remote-docker-daemons).

**I haven't tried this myself**.

In theory, this should work
(you have to replace ip with a valid IP and maybe the path to id_rsa file).

```cs
var file = Path.Combine(Directory.GetCurrentDirectory(),
                (TemplateString) "Resources/ComposeTests/WordPress/docker-compose.yml");

            using (
                var svc =
                    new Builder().UseHost()
                        .UseSsh("192.168.1.27").WithName("remote-daemon")
                        .WithSshUser("solo").WithSshKeyPath("${E_LOCALAPPDATA}/lxss/home/martoffi/.ssh/id_rsa")
                        .UseContainer()
                        .UseCompose()
                        .FromFile(file)
                        .RemoveOrphans()
                        .Build().Start())
            {
            }
```
where the compose file looks like this
```yaml
version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data:
```

You need to have docker on the remote host. Otherwise you can use plain commands maybe like this:

```cs
      var file = Path.Combine(Directory.GetCurrentDirectory(),
                (TemplateString) "Resources/ComposeTests/WordPress/docker-compose.yml");

      var res = "test-machine".Create(1024, 20000, 1);
      var start = "test-machine".Start();
      var ep= new Hosts().FromMachineName("test-machine").First();

      // ep.Host is the URL to machine
      ep.Host.ComposeUp(composeFile: file, certificates: ep.Certificates);
```


Have a go at it if you have the time and please give feedback if it worked or if you needed to do something else to make it work.

Cheers,
 Mario
