### ISSUE TITLE
DockerComposeCompositeService.ExtractNames fails for container names with other format

### ISSUE THREAD

**Issue by msdeibel** [mariotoffia/FluentDocker#94]
` private static string ExtractNames(Container container, out string project, out string instanceId)` fails when called with a container name like `kafka`.

The result is a ArrayIndexOutOfBoundsException in line 155.

It expects a structure like `project_component1_instanceId` as name.
Why this structure is expected is not clear from looking at the method itself.
Also this is not a naming convention from Docker.

I do not have a patch since I don't know what the expected behaviour should be in case of a name that deviates from the structure currently expected by the method.

**Comment by mariotoffia** [comment]
Hi what name does `docker-compose` give your containers?

 For example, given this _docker-compose.yaml_ file
```yaml
version: "3"
services:
    wordpress:
        image: visiblevc/wordpress
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        security_opt:
            - apparmor:unconfined
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./data:/data
            - ./scripts:/docker-entrypoint-initwp.d
            - ./plugins/skelleftetekniken-contest:/app/wp-content/plugins/skelleftetekniken-contest
        depends_on:
            - db
        links:
            - db
        environment:
            DB_NAME: wordpress
            DB_PASS: root
            PLUGINS: >-
                academic-bloggers-toolkit
                co-authors-plus
                wp-file-manager
                [WP-API]https://github.com/WP-API/WP-API/archive/master.zip
            URL_REPLACE: localhost:8080
            WP_DEBUG: 'true'
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG_LOG: 'true'
    db:
        image: mysql:5.7
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22222:80
volumes:
    data:
```

`docker-compose` gives me the following names on the containers. 
```
C:\progs\wordpress\skelleftetekniken>docker-compose up
Creating network "skelleftetekniken_default" with the default driver
Creating skelleftetekniken_phpmyadmin_1 ... done
Creating skelleftetekniken_db_1         ... done
Creating skelleftetekniken_wordpress_1  ... done
```
How are you firing up the containers and what names do they get?

Cheers,
 Mario

**Comment by msdeibel** [comment]
With docker-compose.yml
```
version: '3.5'

services:
  
  # building up the message queue system (zookeeper + kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - messageBus
    ports:
        - "2181:2181"
    restart: always

  kafkaserver:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - messageBus
    ports:
        - 9092:9092
        - 29092:29092
        - 29093:29093
        
    restart: always
    
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181    
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST_DEMOSRV:PLAINTEXT,PLAINTEXT_LOCALHOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST_DEMOSRV://:29092,PLAINTEXT_LOCALHOST://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST_DEMOSRV://demo01:29092,PLAINTEXT_LOCALHOST://localhost:29093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # overrides the default separator ',' for creating topics
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      # create topic "Values" that will use log compaction to get rid of older value messages
      KAFKA_CREATE_TOPICS: |
        Values:1:1:compact --config=min.compaction.lag.ms=250 --config=segment.bytes=536870912 --config=segment.ms=10000 --config=retention.ms=10000 --config=min.cleanable.dirty.ratio=0.25 --config=file.delete.delay.ms=0
        Configuration:1:1:delete --config=file.delete.delay.ms=0 --config=retention.bytes=-1 --config=retention.ms=-1
        ProjectDefinition:1:1:delete --config=file.delete.delay.ms=0 --config=retention.bytes=-1 --config=retention.ms=-1
        SetValues:1:1:delete --config=retention.ms=1000 --config=segment.ms=1000 --config=segment.bytes=268435456 --config=min.cleanable.dirty.ratio=0.1 --config=file.delete.delay.ms=0
        Devices:1:1:delete --config=file.delete.delay.ms=0 --config=retention.bytes=-1 --config=retention.ms=-1
        ReadHistoryValues:1:1:delete --config=retention.ms=1000 --config=segment.ms=1000 --config=segment.bytes=268435456 --config=min.cleanable.dirty.ratio=0.1 --config=file.delete.delay.ms=0 
      
      # Enables/disables the possibility to delete a topic (if set to false, the topic will only be marked for deletion but not deleted actually)
      KAFKA_DELETE_TOPIC_ENABLE: "true"

networks:
  default:
    external:
      name: nat
  
  # create network for messaging
  messageBus:
    name: message-bus
```

and starting up with docker-compose:
```
PS C:\path\to\docker-compose.yml> docker-compose up
Creating zookeeper ... done
Creating kafka     ... done
Attaching to kafka, zookeeper
```

I guess the `container_name` directive leads overrides the defaults that compose would otherwise give to the containers as in your case.
